[tox]
env_list =
    django52
    django60

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest
    pytest-django
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
commands =
    pytest -v --junit-xml=test-report.xml
